### PR TITLE
Make falco file output really optional

### PR DESCRIPTION
**Pull request by claviola**
Based on the behavior of the `falco::config` class, it seems like this was the original intention.

### CODE REVIEW

**Comment by claviola** [comment]
I don't know why the test suite is failing, but it doesn't seem at all related to this change.

**Comment by claviola** [comment]
@bastelfreak @genebean is there anything else that needs to be done for this to be merged?

**Review by smortex — APPROVED** [review]
LGTM

Maybe we can add a test that set it to false so that it does not break again in the future?

**Comment by claviola** [comment]
@smortex @bastelfreak can you review the tests I added?

**Pull request merged**
